### ISSUE TITLE
Auto renew or notification

### ISSUE THREAD

**Issue by alekslyse** [martinohansen/ynabber#54]
What would be the best way to renew the requisitions? It's easy to forget if one expires at least if it needs to be renewed monthly. Is it any way to automatically extend the renewal time so we don't have to renew it?

Or maybe a way to send pull a simple API how many days until it needs to be renewed?

**Comment by martinohansen** [comment]
The current flow is not great, my bank gives me a 90 day (I think) requisition so it have not been horrible for me, but surely its not great.

I've setup it up so I get a email if the word "requisition" appears in the log, and the email contains the log line so I can start the authentication directly from there. 

It's been easy for me to do it like that because I already had this stuff at hand. I'm aware that not everyone have that. 

I'm open to ideas and I might have some time to help implement it if it comes to that.

**Comment by hpernu** [comment]
Due to the way PSD2 and/or Nordigen API is defined, the absolute maximum you can get for renewal is 90 days which is what I commonly have. There might be banks which make this even shorter although I have not come across such.
So by definition it cannot be extended beyond 90 days.

What I've done I'm actually running ynabber on schedule i.e. it is not on all the time. The actual requisition data and configurations are kept in version control. Once these scheduled runs start getting errors, I check what is the problem, and, if the requisition is outdated, I relogin on my workstation and save the requisiton data to version control. Everything then works smoothly for that bank for 90 days again (although sometimes there are transient errors such as bank connection maintenance breaks).

But if you're keeping ynabber running constantly, there are log follow solutions available. I've worked with multiple such solutions but most of them are more suitable for enterprise setting. I am sure, however, that something could be retrofitted to serve this purpose and even post results to e-mail, Teams, or whatever is your choice.

Because there are so many ways people might want this, personally I do not see much added benefit in implementing an API for this. There might be some kind of status checking thing (a simple webserver?) returning json but beyond that it really is a question of how you want these notifications to get. I am also sure, if it is simple and generic enough, an implementation patch could be accepted by Martin.

And no, requistion renewal cannot be made automatic, as this is exactly the purpose why PSD2 (and Nordigen) is made as it is. So you do have to reauthenticate yourself once in a while.

**Comment by CanYumusak** [comment]
The cleanest/best way to solve this is to send a notification to ones phone when the requisition is close to expiring. A user should then be notified ~ a week before expiry with daily pushes. Users could then fulfill the requisition on their phone and ynabber would grasp the new one automatically.

So the thing is in order to implement this, we need:
* Ynabber running as a webserver, which gets notified once the user fulfills the new requisition via redirect
* Some push service that users can install on their phone, I personally like https://logsnag.com/

I know this is a rather big feature, I'll try to have a stab at it if I get some time on my hands

**Comment by martinohansen** [comment]
> The cleanest/best way to solve this is to send a notification to ones phone when the requisition is close to expiring. A user should then be notified ~ a week before expiry with daily pushes. Users could then fulfill the requisition on their phone and ynabber would grasp the new one automatically.

I like that, having a daemon running in the background monitoring the requisition and creating a new one before the old one expires would be super nice.

I have a few inputs to the proposed implementation: 

> Ynabber running as a webserver, which gets notified once the user fulfills the new requisition via redirect

Currently, we check if the requisition has been fulfilled on a timely interval, I think we should keep it that way to avoid adding the complexity of a webserver. The nature of the program won't require us to know the requisition status immediately as it changes.

> Some push service that users can install on their phone, I personally like https://logsnag.com/

It would be nice if we could separate the various notification services like logsnag and Ynabber. One way I can think of is making a simple exec call with a standard set of arguments and let it be up to the user to implement a program that sends the notification to whatever they like. 

We could provide a few programs (shell scripts or something akin) for use or as examples to new implementations. 
 
> I know this is a rather big feature, I'll try to have a stab at it if I get some time on my hands

Thanks for taking the time to think about this, I appreciate it. Let me know what you think of my suggestion.

**Comment by CanYumusak** [comment]
Thanks for the swift response!

> The nature of the program won't require us to know the requisition status immediately as it changes.

That's absolutely right - we don't need to fetch that instantly. WIll also take away a bunch of complexity of users setting YNAB up (no nginx config etc etc).

> It would be nice if we could separate the various notification services like logsnag and Ynabber

I understand the wish for this, I'm not sure how to make it great though. If it was me, I would probably try to make the notification layer agnostic of a tool and provide a single implementation (logsnag or any other tool that does not require setup). Devs could add more notification solutions and the user could configure it in the env file. This nudges users into a "do-it-all-without-making-me-work" solution but keeps the door open for more. I do understand though that forcing users into a tool is not something you wish to do.

> Thanks for taking the time to think about this

I'd be also happy if you take this though - during some playaround earlier I found out that Go is more foreign to my skillset than I anticipated. I'm also happy to learn new stuff though.

**Comment by hpernu** [comment]
As a contributor to the code, my ideas: try to keep this as simple as possible i.e. UNIX-philosophy. Thus  I am voting for a separate tool to handle this stuff and only provide 'hooks' - that is, for example a path to script. Sometimes a better alternative though would be a parameterized URL: this is especially useful, if using the docker container version.
I could also work with the requisition URL being appended to a file.

That would thus give the following options:
- an URL that is called (although what is sent as payload is then an open question)
- writing the requisition URL on a file (which might be named pipe which the user can then himself work on listening and providing a solution for handling the requisition)
- a shell script/command on the file system
- the way it is  now (i.e. printing the URL on logs)

I really do NOT want notifications on my phone and don't know anything about the idea first suggested. 
My specific use case is somewhat different than most, however. I actually use ynabber for multiple banks and accounts for two different users (from banking perspective) which all go to same YNAB instance. Furthermore, I run ynabber periodically (every hour approximately) rather than in constant polling mode. Once I see one of the bank connection failing, I manually reauthenticate. 

I can see how this could work if I got the URL to Signal. But even then, I am unlikely to authenticate within the current 10 minute timeout and my use case would probably spam me constantly. Worst case, I might have tens of messages in the morning. I don't read my messages constantly. Also this already tells that we have likely a multitude of different ways the messaging could be handled. Adding any one of them would open the door to requesting multiple solutions: so make it the most generic and simple and let other people(or team) work on message passing tools.

**Comment by CanYumusak** [comment]
In order to solve for the less controversial part I propose the following PR to support notifications: https://github.com/martinohansen/ynabber/pull/56

It's not mandatory and takes in a shell script, as suggested. 

Regarding concerns around notifications, timeouts, and so on: Tons of great input in this thread! I do believe that most concerns can be addressed though

**Comment by hpernu** [comment]
I added some comments. The more I think about it, the more likely I am to actually approve. Although it has several issues especially when running inside docker ( I am not even sure your example would work. Is there docker installed on the sparse ynabber docker image? ) it is nonetheless a solution which serves your purpose and this is open source after all.
As long as it does not become overly complicated, anybody who is willing should get to do something. :)

But I'll let @martinohansen be a the final approver.

**Comment by martinohansen** [comment]
Solved by the requisition hook in v0.7.0 🎉
